# Generated by Django 6.0.7 on 2026-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(help_text='Ex: VT, ABUSEIPDB', max_length=50, unique=True)),
                ('cle_api', models.CharField(help_text='La clé secrète fournie par le fournisseur', max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('quota_restant', models.IntegerField(default=1000)),
                ('quota_consomme', models.IntegerField(default=0)),
                ('date_derniere_utilisation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
