# Generated by Django 6.0.7 on 2026-07-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_analyzer', '0002_configurationapi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatindicator',
            name='created_at',
        ),
        migrations.AddField(
            model_name='threatindicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='threatindicator',
            name='description',
            field=models.TextField(default='Ancienne analyse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threatindicator',
            name='indicator_type',
            field=models.CharField(choices=[('IP', 'Adresse IP'), ('DOMAINE', 'Nom de Domaine'), ('HASH', 'Fichier Hash'), ('CVE', 'Vulnérabilité CVE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='threatindicator',
            name='indicator_value',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='threat_analyzer.threatindicator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
