# Generated by Django 6.0.7 on 2026-08-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_analyzer', '0003_remove_threatindicator_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threatindicator',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, help_text='Analyste ayant ajouté manuellement cet IOC (vide si scan automatique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iocs_ajoutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatindicator',
            name='source',
            field=models.CharField(choices=[('SCAN_AUTO', 'Scan automatique (API)'), ('PARE_FEU', 'Pare-feu'), ('SIEM', 'SIEM'), ('RENSEIGNEMENT_EXTERNE', 'Renseignement externe'), ('INVESTIGATION_MANUELLE', 'Investigation manuelle'), ('AUTRE', 'Autre')], default='SCAN_AUTO', max_length=30),
        ),
    ]
