# Generated by Django 6.0.7 on 2026-08-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_analyzer', '0004_threatindicator_ajoute_par_threatindicator_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirme_le', models.DateTimeField(auto_now_add=True)),
                ('confirme_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menaces_confirmees', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menace', to='threat_analyzer.threatindicator')),
            ],
        ),
        migrations.CreateModel(
            name='FileDeploiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploiements_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('menace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deploiement', to='threat_analyzer.menace')),
            ],
        ),
    ]
