# Generated by Django 6.0.7 on 2026-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_analyzer', '0006_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocalisationIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('code_pays', models.CharField(blank=True, max_length=2)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('introuvable', models.BooleanField(default=False)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
